create database customer_shopping_behavior_analysis;
use customer_shopping_behavior_analysis;


-- 1. what is the total revenue generated by male vs female customers
SELECT gender,sum(purchase_amount_usd) as revenue
from customer_shopping_behavior_analysis.customer_shopping_behavior
group by gender;


-- 2. which customer used a discount and still spent more than the average purchase amount
select customer_id, purchase_amount_usd
from customer_shopping_behavior_analysis.customer_shopping_behavior
where Discount_Applied = "yes" and Purchase_Amount_USD >=(select avg(Purchase_Amount_USD) 
from customer_shopping_behavior_analysis.customer_shopping_behavior);


-- 3. which are the top 5 products with highest avg review rating
select item_purchased, avg(review_rating) as "average product rating" 
from customer_shopping_behavior_analysis.customer_shopping_behavior
group by Item_Purchased
order by avg(Review_Rating) desc
limit 5;


-- 4. compare the avg purchase amounts between standard and express shipping 
select shipping_type, 
round(avg(purchase_amount_usd),2)
from customer_shopping_behavior_analysis.customer_shopping_behavior
where shipping_type in ('standard','express')
group by Shipping_Type;



-- 5. do subscribe customers spend more? compare avg spend and total revenue between subscribers and non subscribers 
select Subscription_Status,
count(customer_id) as total_customers,
round(avg(purchase_amount_usd),2) as avg_spend,
round(sum(purchase_amount_usd),2) as total_revenue
from customer_shopping_behavior_analysis.customer_shopping_behavior
group by Subscription_Status
order by total_revenue, avg_spend desc;


-- 6. which 5 products have highest percentage of purchase with discount applied 
SELECT Item_Purchased,ROUND((SUM(CASE WHEN Discount_Applied = 'Yes' THEN 1 ELSE 0 END) * 100.0) 
/ COUNT(*), 2) AS Discount_Percentage
FROM customer_shopping_behavior_analysis.customer_shopping_behavior
GROUP BY Item_Purchased
ORDER BY Discount_Percentage DESC
LIMIT 5;


-- 7. segments customers into new, returning and loyal based on their total number of previous
-- purchases, and show the count of each segment
SELECT CASE
WHEN Previous_Purchases = 1 THEN 'New Customer'
WHEN Previous_Purchases BETWEEN 2 AND 10 THEN 'Returning Customer'
ELSE 'Loyal Customer'
END AS Customer_Segment,
COUNT(*) AS Total_Customers
FROM customer_shopping_behavior_analysis.customer_shopping_behavior
GROUP BY Customer_Segment;


-- 8. what are the top 3 most purchase products within each category
SELECT Category,
Item_Purchased,
COUNT(*) AS Total_Purchases
FROM customer_shopping_behavior_analysis.customer_shopping_behavior
GROUP BY Category, Item_Purchased
ORDER BY Category, Total_Purchases DESC
LIMIT 3;


-- 9. are customers who are repeat buyers(more than 5 previous purchases), also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers 
from  customer_shopping_behavior_analysis.customer_shopping_behavior
where previous_purchases > 5
group by Subscription_Status;


-- 10. what is the revenue contribution of each age group
select age, 
sum(purchase_amount_usd) as total_revenue
from customer_shopping_behavior_analysis.customer_shopping_behavior
group by age
order by total_revenue desc;










